import type { Space } from "@/lib/spaces";

export function makeSpace(overrides: Partial<Space> = {}): Space {
  return {
    id: "space-1",
    slug: "space-1",
    name: "Entréhallen",
    name_en: "Entrance Hall",
    space_kind: "study",
    category: "study",
    description: "",
    description_en: null,
    description_inline: false,
    intent: [],
    noise: [],
    equipment: [],
    facilities: [],
    lokaltyp: ["Studieplats"],
    image_url: null,
    images: [],
    image_alts: [],
    image_alts_en: [],
    map_url: null,
    map_url_en: null,
    booking_url: null,
    booking_url_en: null,
    group_booking_url: null,
    group_booking_url_en: null,
    book_now_url: null,
    book_now_url_en: null,
    sort_order: 0,
    floor: null,
    floor_en: null,
    located_in: null,
    located_in_en: null,
    capacity: null,
    computer_count: null,
    informal_seat_count: null,
    tags: {},
    notice: null,
    notice_en: null,
    info: null,
    info_en: null,
    show_capacity_publicly: true,
    show_occupancy: false,
    countmatters_sensor_id: null,
    booking_room_number: null,
    hidden: false,
    ...overrides,
  };
}
